# ----------- CONFIGURABLE START -----------
title:            "Wild Wikis of the West"
description:      "Wild wikis of the west"
url:              https://www.wildwikis.com # Site url, without a slash at the end.
signoff:          "Andrew G" # Your name
google_analytics: # Set tracking, remove from /javascripts/basic.js if unwanted.
future: false
links:
  - name:         Home
    url:          /
    external:     false
  - name:         Archive
    url:          /archive.html
    external:     false
  - name:         About
    url:          /about.html
    external:     false
  - name:         Submit
    url:          /submit.html
    external:     false
# ------------ CONFIGURABLE END ------------

defaults:
  - values:
      layout: "default"